"""
ATT&CK TTP extraction from article text.

Two-pass approach:
  1. Regex  — free, instant; finds explicitly cited T-IDs (e.g. T1566.001)
  2. Claude — semantic; infers techniques from prose descriptions

Both passes are merged and deduplicated by technique_id.
Claude pass is skipped when ANTHROPIC_API_KEY is absent.
Regex pass auto-populates technique_name and tactic from TECHNIQUE_LOOKUP.
"""

import re
import json

TECHNIQUE_RE = re.compile(r'\b(T\d{4}(?:\.\d{3})?)\b')

MAX_ARTICLES_PER_RUN = 30   # cost guard: max AI calls per pipeline run
MAX_TEXT_CHARS       = 4000  # truncate article to keep token costs low

TECHNIQUE_LOOKUP: dict[str, dict] = {
    "T1056.002": {"name": "GUI Input Capture", "tactic": "collection"},
    "T1056.003": {"name": "Web Portal Capture", "tactic": "collection"},
    "T1056.004": {"name": "Credential API Hooking", "tactic": "collection"},
    "T1057": {"name": "Process Discovery", "tactic": "discovery"},
    "T1059": {"name": "Command and Scripting Interpreter", "tactic": "execution"},
    "T1059.001": {"name": "PowerShell", "tactic": "execution"},
    "T1059.002": {"name": "AppleScript", "tactic": "execution"},
    "T1059.003": {"name": "Windows Command Shell", "tactic": "execution"},
    "T1059.004": {"name": "Unix Shell", "tactic": "execution"},
    "T1059.005": {"name": "Visual Basic", "tactic": "execution"},
    "T1059.006": {"name": "Python", "tactic": "execution"},
    "T1059.007": {"name": "JavaScript", "tactic": "execution"},
    "T1059.008": {"name": "Network Device CLI", "tactic": "execution"},
    "T1059.009": {"name": "Cloud API", "tactic": "execution"},
    "T1059.010": {"name": "AutoHotKey & AutoIT", "tactic": "execution"},
    "T1059.011": {"name": "Lua", "tactic": "execution"},
    "T1059.012": {"name": "Hypervisor CLI", "tactic": "execution"},
    "T1059.013": {"name": "Container CLI/API", "tactic": "execution"},
    "T1068": {"name": "Exploitation for Privilege Escalation", "tactic": "privilege-escalation"},
    "T1069": {"name": "Permission Groups Discovery", "tactic": "discovery"},
    "T1069.001": {"name": "Local Groups", "tactic": "discovery"},
    "T1069.002": {"name": "Domain Groups", "tactic": "discovery"},
    "T1069.003": {"name": "Cloud Groups", "tactic": "discovery"},
    "T1070": {"name": "Indicator Removal", "tactic": "defense-evasion"},
    "T1070.003": {"name": "Clear Command History", "tactic": "defense-evasion"},
    "T1070.004": {"name": "File Deletion", "tactic": "defense-evasion"},
    "T1070.005": {"name": "Network Share Connection Removal", "tactic": "defense-evasion"},
    "T1070.006": {"name": "Timestomp", "tactic": "defense-evasion"},
    "T1070.007": {"name": "Clear Network Connection History and Configurations", "tactic": "defense-evasion"},
    "T1070.008": {"name": "Clear Mailbox Data", "tactic": "defense-evasion"},
    "T1070.009": {"name": "Clear Persistence", "tactic": "defense-evasion"},
    "T1070.010": {"name": "Relocate Malware", "tactic": "defense-evasion"},
    "T1071": {"name": "Application Layer Protocol", "tactic": "command-and-control"},
    "T1071.001": {"name": "Web Protocols", "tactic": "command-and-control"},
    "T1071.002": {"name": "File Transfer Protocols", "tactic": "command-and-control"},
    "T1071.003": {"name": "Mail Protocols", "tactic": "command-and-control"},
    "T1071.004": {"name": "DNS", "tactic": "command-and-control"},
    "T1071.005": {"name": "Publish/Subscribe Protocols", "tactic": "command-and-control"},
    "T1072": {"name": "Software Deployment Tools", "tactic": "execution"},
    "T1074": {"name": "Data Staged", "tactic": "collection"},
    "T1074.001": {"name": "Local Data Staging", "tactic": "collection"},
    "T1074.002": {"name": "Remote Data Staging", "tactic": "collection"},
    "T1078": {"name": "Valid Accounts", "tactic": "defense-evasion"},
    "T1078.001": {"name": "Default Accounts", "tactic": "defense-evasion"},
    "T1078.002": {"name": "Domain Accounts", "tactic": "defense-evasion"},
    "T1078.003": {"name": "Local Accounts", "tactic": "defense-evasion"},
    "T1078.004": {"name": "Cloud Accounts", "tactic": "defense-evasion"},
    "T1080": {"name": "Taint Shared Content", "tactic": "lateral-movement"},
    "T1082": {"name": "System Information Discovery", "tactic": "discovery"},
    "T1083": {"name": "File and Directory Discovery", "tactic": "discovery"},
    "T1087": {"name": "Account Discovery", "tactic": "discovery"},
    "T1087.001": {"name": "Local Account", "tactic": "discovery"},
    "T1087.002": {"name": "Domain Account", "tactic": "discovery"},
    "T1087.003": {"name": "Email Account", "tactic": "discovery"},
    "T1087.004": {"name": "Cloud Account", "tactic": "discovery"},
    "T1090": {"name": "Proxy", "tactic": "command-and-control"},
    "T1090.001": {"name": "Internal Proxy", "tactic": "command-and-control"},
    "T1090.002": {"name": "External Proxy", "tactic": "command-and-control"},
    "T1090.003": {"name": "Multi-hop Proxy", "tactic": "command-and-control"},
    "T1090.004": {"name": "Domain Fronting", "tactic": "command-and-control"},
    "T1091": {"name": "Replication Through Removable Media", "tactic": "initial-access"},
    "T1092": {"name": "Communication Through Removable Media", "tactic": "command-and-control"},
    "T1095": {"name": "Non-Application Layer Protocol", "tactic": "command-and-control"},
    "T1098": {"name": "Account Manipulation", "tactic": "persistence"},
    "T1098.001": {"name": "Additional Cloud Credentials", "tactic": "persistence"},
    "T1098.002": {"name": "Additional Email Delegate Permissions", "tactic": "persistence"},
    "T1098.003": {"name": "Additional Cloud Roles", "tactic": "persistence"},
    "T1098.004": {"name": "SSH Authorized Keys", "tactic": "persistence"},
    "T1098.005": {"name": "Device Registration", "tactic": "persistence"},
    "T1098.006": {"name": "Additional Container Cluster Roles", "tactic": "persistence"},
    "T1098.007": {"name": "Additional Local or Domain Groups", "tactic": "persistence"},
    "T1102": {"name": "Web Service", "tactic": "command-and-control"},
    "T1102.001": {"name": "Dead Drop Resolver", "tactic": "command-and-control"},
    "T1102.002": {"name": "Bidirectional Communication", "tactic": "command-and-control"},
    "T1102.003": {"name": "One-Way Communication", "tactic": "command-and-control"},
    "T1104": {"name": "Multi-Stage Channels", "tactic": "command-and-control"},
    "T1105": {"name": "Ingress Tool Transfer", "tactic": "command-and-control"},
    "T1106": {"name": "Native API", "tactic": "execution"},
    "T1110": {"name": "Brute Force", "tactic": "credential-access"},
    "T1110.001": {"name": "Password Guessing", "tactic": "credential-access"},
    "T1110.002": {"name": "Password Cracking", "tactic": "credential-access"},
    "T1110.003": {"name": "Password Spraying", "tactic": "credential-access"},
    "T1110.004": {"name": "Credential Stuffing", "tactic": "credential-access"},
    "T1111": {"name": "Multi-Factor Authentication Interception", "tactic": "credential-access"},
    "T1112": {"name": "Modify Registry", "tactic": "defense-evasion"},
    "T1113": {"name": "Screen Capture", "tactic": "collection"},
    "T1114": {"name": "Email Collection", "tactic": "collection"},
    "T1114.001": {"name": "Local Email Collection", "tactic": "collection"},
    "T1114.002": {"name": "Remote Email Collection", "tactic": "collection"},
    "T1114.003": {"name": "Email Forwarding Rule", "tactic": "collection"},
    "T1115": {"name": "Clipboard Data", "tactic": "collection"},
    "T1119": {"name": "Automated Collection", "tactic": "collection"},
    "T1120": {"name": "Peripheral Device Discovery", "tactic": "discovery"},
    "T1123": {"name": "Audio Capture", "tactic": "collection"},
    "T1124": {"name": "System Time Discovery", "tactic": "discovery"},
    "T1125": {"name": "Video Capture", "tactic": "collection"},
    "T1127": {"name": "Trusted Developer Utilities Proxy Execution", "tactic": "defense-evasion"},
    "T1127.001": {"name": "MSBuild", "tactic": "defense-evasion"},
    "T1127.002": {"name": "ClickOnce", "tactic": "defense-evasion"},
    "T1127.003": {"name": "JamPlus", "tactic": "defense-evasion"},
    "T1129": {"name": "Shared Modules", "tactic": "execution"},
    "T1132": {"name": "Data Encoding", "tactic": "command-and-control"},
    "T1132.001": {"name": "Standard Encoding", "tactic": "command-and-control"},
    "T1132.002": {"name": "Non-Standard Encoding", "tactic": "command-and-control"},
    "T1133": {"name": "External Remote Services", "tactic": "initial-access"},
    "T1134": {"name": "Access Token Manipulation", "tactic": "defense-evasion"},
    "T1134.001": {"name": "Token Impersonation/Theft", "tactic": "defense-evasion"},
    "T1134.002": {"name": "Create Process with Token", "tactic": "defense-evasion"},
    "T1134.003": {"name": "Make and Impersonate Token", "tactic": "defense-evasion"},
    "T1134.004": {"name": "Parent PID Spoofing", "tactic": "defense-evasion"},
    "T1134.005": {"name": "SID-History Injection", "tactic": "defense-evasion"},
    "T1135": {"name": "Network Share Discovery", "tactic": "discovery"},
    "T1136": {"name": "Create Account", "tactic": "persistence"},
    "T1136.001": {"name": "Local Account", "tactic": "persistence"},
    "T1136.002": {"name": "Domain Account", "tactic": "persistence"},
    "T1136.003": {"name": "Cloud Account", "tactic": "persistence"},
    "T1137": {"name": "Office Application Startup", "tactic": "persistence"},
    "T1137.001": {"name": "Office Template Macros", "tactic": "persistence"},
    "T1137.002": {"name": "Office Test", "tactic": "persistence"},
    "T1137.003": {"name": "Outlook Forms", "tactic": "persistence"},
    "T1137.004": {"name": "Outlook Home Page", "tactic": "persistence"},
    "T1137.005": {"name": "Outlook Rules", "tactic": "persistence"},
    "T1137.006": {"name": "Add-ins", "tactic": "persistence"},
    "T1140": {"name": "Deobfuscate/Decode Files or Information", "tactic": "defense-evasion"},
    "T1176": {"name": "Software Extensions", "tactic": "persistence"},
    "T1176.001": {"name": "Browser Extensions", "tactic": "persistence"},
    "T1176.002": {"name": "IDE Extensions", "tactic": "persistence"},
    "T1185": {"name": "Browser Session Hijacking", "tactic": "collection"},
    "T1187": {"name": "Forced Authentication", "tactic": "credential-access"},
    "T1189": {"name": "Drive-by Compromise", "tactic": "initial-access"},
    "T1190": {"name": "Exploit Public-Facing Application", "tactic": "initial-access"},
    "T1195": {"name": "Supply Chain Compromise", "tactic": "initial-access"},
    "T1195.001": {"name": "Compromise Software Dependencies and Development Tools", "tactic": "initial-access"},
    "T1195.002": {"name": "Compromise Software Supply Chain", "tactic": "initial-access"},
    "T1195.003": {"name": "Compromise Hardware Supply Chain", "tactic": "initial-access"},
    "T1197": {"name": "BITS Jobs", "tactic": "defense-evasion"},
    "T1199": {"name": "Trusted Relationship", "tactic": "initial-access"},
    "T1200": {"name": "Hardware Additions", "tactic": "initial-access"},
    "T1201": {"name": "Password Policy Discovery", "tactic": "discovery"},
    "T1202": {"name": "Indirect Command Execution", "tactic": "defense-evasion"},
    "T1203": {"name": "Exploitation for Client Execution", "tactic": "execution"},
    "T1204": {"name": "User Execution", "tactic": "execution"},
    "T1204.001": {"name": "Malicious Link", "tactic": "execution"},
    "T1204.002": {"name": "Malicious File", "tactic": "execution"},
    "T1204.003": {"name": "Malicious Image", "tactic": "execution"},
    "T1204.004": {"name": "Malicious Copy and Paste", "tactic": "execution"},
    "T1204.005": {"name": "Malicious Library", "tactic": "execution"},
    "T1205": {"name": "Traffic Signaling", "tactic": "command-and-control"},
    "T1205.001": {"name": "Port Knocking", "tactic": "command-and-control"},
    "T1205.002": {"name": "Socket Filters", "tactic": "command-and-control"},
    "T1210": {"name": "Exploitation of Remote Services", "tactic": "lateral-movement"},
    "T1211": {"name": "Exploitation for Stealth", "tactic": "defense-evasion"},
    "T1212": {"name": "Exploitation for Credential Access", "tactic": "credential-access"},
    "T1213": {"name": "Data from Information Repositories", "tactic": "collection"},
    "T1213.001": {"name": "Confluence", "tactic": "collection"},
    "T1213.002": {"name": "Sharepoint", "tactic": "collection"},
    "T1213.003": {"name": "Code Repositories", "tactic": "collection"},
    "T1213.004": {"name": "Customer Relationship Management Software", "tactic": "collection"},
    "T1213.005": {"name": "Messaging Applications", "tactic": "collection"},
    "T1213.006": {"name": "Databases", "tactic": "collection"},
    "T1216": {"name": "System Script Proxy Execution", "tactic": "defense-evasion"},
    "T1216.001": {"name": "PubPrn", "tactic": "defense-evasion"},
    "T1216.002": {"name": "SyncAppvPublishingServer", "tactic": "defense-evasion"},
    "T1217": {"name": "Browser Information Discovery", "tactic": "discovery"},
    "T1218": {"name": "System Binary Proxy Execution", "tactic": "defense-evasion"},
    "T1218.001": {"name": "Compiled HTML File", "tactic": "defense-evasion"},
    "T1218.002": {"name": "Control Panel", "tactic": "defense-evasion"},
    "T1218.003": {"name": "CMSTP", "tactic": "defense-evasion"},
    "T1218.004": {"name": "InstallUtil", "tactic": "defense-evasion"},
    "T1218.005": {"name": "Mshta", "tactic": "defense-evasion"},
    "T1218.007": {"name": "Msiexec", "tactic": "defense-evasion"},
    "T1218.008": {"name": "Odbcconf", "tactic": "defense-evasion"},
    "T1218.009": {"name": "Regsvcs/Regasm", "tactic": "defense-evasion"},
    "T1218.010": {"name": "Regsvr32", "tactic": "defense-evasion"},
    "T1218.011": {"name": "Rundll32", "tactic": "defense-evasion"},
    "T1218.012": {"name": "Verclsid", "tactic": "defense-evasion"},
    "T1218.013": {"name": "Mavinject", "tactic": "defense-evasion"},
    "T1218.014": {"name": "MMC", "tactic": "defense-evasion"},
    "T1218.015": {"name": "Electron Applications", "tactic": "defense-evasion"},
    "T1219": {"name": "Remote Access Tools", "tactic": "command-and-control"},
    "T1219.001": {"name": "IDE Tunneling", "tactic": "command-and-control"},
    "T1219.002": {"name": "Remote Desktop Software", "tactic": "command-and-control"},
    "T1219.003": {"name": "Remote Access Hardware", "tactic": "command-and-control"},
    "T1220": {"name": "XSL Script Processing", "tactic": "defense-evasion"},
    "T1221": {"name": "Template Injection", "tactic": "defense-evasion"},
    "T1482": {"name": "Domain Trust Discovery", "tactic": "discovery"},
    "T1484": {"name": "Domain or Tenant Policy Modification", "tactic": "defense-evasion"},
    "T1484.001": {"name": "Group Policy Modification", "tactic": "defense-evasion"},
    "T1484.002": {"name": "Trust Modification", "tactic": "defense-evasion"},
    "T1485": {"name": "Data Destruction", "tactic": "impact"},
    "T1485.001": {"name": "Lifecycle-Triggered Deletion", "tactic": "impact"},
    "T1486": {"name": "Data Encrypted for Impact", "tactic": "impact"},
    "T1489": {"name": "Service Stop", "tactic": "impact"},
    "T1490": {"name": "Inhibit System Recovery", "tactic": "impact"},
    "T1491": {"name": "Defacement", "tactic": "impact"},
    "T1491.001": {"name": "Internal Defacement", "tactic": "impact"},
    "T1491.002": {"name": "External Defacement", "tactic": "impact"},
    "T1495": {"name": "Firmware Corruption", "tactic": "impact"},
    "T1496": {"name": "Resource Hijacking", "tactic": "impact"},
    "T1496.001": {"name": "Compute Hijacking", "tactic": "impact"},
    "T1496.002": {"name": "Bandwidth Hijacking", "tactic": "impact"},
    "T1496.003": {"name": "SMS Pumping", "tactic": "impact"},
    "T1496.004": {"name": "Cloud Service Hijacking", "tactic": "impact"},
    "T1497": {"name": "Virtualization/Sandbox Evasion", "tactic": "defense-evasion"},
    "T1497.001": {"name": "System Checks", "tactic": "defense-evasion"},
    "T1497.002": {"name": "User Activity Based Checks", "tactic": "defense-evasion"},
    "T1497.003": {"name": "Time Based Checks", "tactic": "defense-evasion"},
    "T1498": {"name": "Network Denial of Service", "tactic": "impact"},
    "T1498.001": {"name": "Direct Network Flood", "tactic": "impact"},
    "T1498.002": {"name": "Reflection Amplification", "tactic": "impact"},
    "T1499": {"name": "Endpoint Denial of Service", "tactic": "impact"},
    "T1499.001": {"name": "OS Exhaustion Flood", "tactic": "impact"},
    "T1499.002": {"name": "Service Exhaustion Flood", "tactic": "impact"},
    "T1499.003": {"name": "Application Exhaustion Flood", "tactic": "impact"},
    "T1499.004": {"name": "Application or System Exploitation", "tactic": "impact"},
    "T1505": {"name": "Server Software Component", "tactic": "persistence"},
    "T1505.001": {"name": "SQL Stored Procedures", "tactic": "persistence"},
    "T1505.002": {"name": "Transport Agent", "tactic": "persistence"},
    "T1505.003": {"name": "Web Shell", "tactic": "persistence"},
    "T1505.004": {"name": "IIS Components", "tactic": "persistence"},
    "T1505.005": {"name": "Terminal Services DLL", "tactic": "persistence"},
    "T1505.006": {"name": "vSphere Installation Bundles", "tactic": "persistence"},
    "T1518": {"name": "Software Discovery", "tactic": "discovery"},
    "T1518.001": {"name": "Security Software Discovery", "tactic": "discovery"},
    "T1518.002": {"name": "Backup Software Discovery", "tactic": "discovery"},
    "T1525": {"name": "Implant Internal Image", "tactic": "persistence"},
    "T1526": {"name": "Cloud Service Discovery", "tactic": "discovery"},
    "T1528": {"name": "Steal Application Access Token", "tactic": "credential-access"},
    "T1529": {"name": "System Shutdown/Reboot", "tactic": "impact"},
    "T1530": {"name": "Data from Cloud Storage", "tactic": "collection"},
    "T1531": {"name": "Account Access Removal", "tactic": "impact"},
    "T1534": {"name": "Internal Spearphishing", "tactic": "lateral-movement"},
    "T1535": {"name": "Unused/Unsupported Cloud Regions", "tactic": "defense-evasion"},
    "T1537": {"name": "Transfer Data to Cloud Account", "tactic": "exfiltration"},
    "T1538": {"name": "Cloud Service Dashboard", "tactic": "discovery"},
    "T1539": {"name": "Steal Web Session Cookie", "tactic": "credential-access"},
    "T1542": {"name": "Pre-OS Boot", "tactic": "defense-evasion"},
    "T1542.001": {"name": "System Firmware", "tactic": "defense-evasion"},
    "T1542.002": {"name": "Component Firmware", "tactic": "defense-evasion"},
    "T1542.003": {"name": "Bootkit", "tactic": "defense-evasion"},
    "T1542.004": {"name": "ROMMONkit", "tactic": "defense-evasion"},
    "T1542.005": {"name": "TFTP Boot", "tactic": "defense-evasion"},
    "T1543": {"name": "Create or Modify System Process", "tactic": "persistence"},
    "T1543.001": {"name": "Launch Agent", "tactic": "persistence"},
    "T1543.002": {"name": "Systemd Service", "tactic": "persistence"},
    "T1543.003": {"name": "Windows Service", "tactic": "persistence"},
    "T1543.004": {"name": "Launch Daemon", "tactic": "persistence"},
    "T1543.005": {"name": "Container Service", "tactic": "persistence"},
    "T1546": {"name": "Event Triggered Execution", "tactic": "persistence"},
    "T1546.001": {"name": "Change Default File Association", "tactic": "persistence"},
    "T1546.002": {"name": "Screensaver", "tactic": "persistence"},
    "T1546.003": {"name": "Windows Management Instrumentation Event Subscription", "tactic": "persistence"},
    "T1546.004": {"name": "Unix Shell Configuration Modification", "tactic": "persistence"},
    "T1546.005": {"name": "Trap", "tactic": "persistence"},
    "T1546.006": {"name": "LC_LOAD_DYLIB Addition", "tactic": "persistence"},
    "T1546.007": {"name": "Netsh Helper DLL", "tactic": "persistence"},
    "T1546.008": {"name": "Accessibility Features", "tactic": "persistence"},
    "T1546.009": {"name": "AppCert DLLs", "tactic": "persistence"},
    "T1546.010": {"name": "AppInit DLLs", "tactic": "persistence"},
    "T1546.011": {"name": "Application Shimming", "tactic": "persistence"},
    "T1546.012": {"name": "Image File Execution Options Injection", "tactic": "persistence"},
    "T1546.013": {"name": "PowerShell Profile", "tactic": "persistence"},
    "T1546.014": {"name": "Emond", "tactic": "persistence"},
    "T1546.015": {"name": "Component Object Model Hijacking", "tactic": "persistence"},
    "T1546.016": {"name": "Installer Packages", "tactic": "persistence"},
    "T1546.017": {"name": "Udev Rules", "tactic": "persistence"},
    "T1546.018": {"name": "Python Startup Hooks", "tactic": "persistence"},
    "T1547": {"name": "Boot or Logon Autostart Execution", "tactic": "persistence"},
    "T1547.001": {"name": "Registry Run Keys / Startup Folder", "tactic": "persistence"},
    "T1547.002": {"name": "Authentication Package", "tactic": "persistence"},
    "T1547.003": {"name": "Time Providers", "tactic": "persistence"},
    "T1547.004": {"name": "Winlogon Helper DLL", "tactic": "persistence"},
    "T1547.005": {"name": "Security Support Provider", "tactic": "persistence"},
    "T1547.006": {"name": "Kernel Modules and Extensions", "tactic": "persistence"},
    "T1547.007": {"name": "Re-opened Applications", "tactic": "persistence"},
    "T1547.008": {"name": "LSASS Driver", "tactic": "persistence"},
    "T1547.009": {"name": "Shortcut Modification", "tactic": "persistence"},
    "T1547.010": {"name": "Port Monitors", "tactic": "persistence"},
    "T1547.012": {"name": "Print Processors", "tactic": "persistence"},
    "T1547.013": {"name": "XDG Autostart Entries", "tactic": "persistence"},
    "T1547.014": {"name": "Active Setup", "tactic": "persistence"},
    "T1547.015": {"name": "Login Items", "tactic": "persistence"},
    "T1548": {"name": "Abuse Elevation Control Mechanism", "tactic": "defense-evasion"},
    "T1548.001": {"name": "Setuid and Setgid", "tactic": "defense-evasion"},
    "T1548.002": {"name": "Bypass User Account Control", "tactic": "defense-evasion"},
    "T1548.003": {"name": "Sudo and Sudo Caching", "tactic": "defense-evasion"},
    "T1548.004": {"name": "Elevated Execution with Prompt", "tactic": "defense-evasion"},
    "T1548.005": {"name": "Temporary Elevated Cloud Access", "tactic": "defense-evasion"},
    "T1548.006": {"name": "TCC Manipulation", "tactic": "defense-evasion"},
    "T1550": {"name": "Use Alternate Authentication Material", "tactic": "defense-evasion"},
    "T1550.001": {"name": "Application Access Token", "tactic": "defense-evasion"},
    "T1550.002": {"name": "Pass the Hash", "tactic": "defense-evasion"},
    "T1550.003": {"name": "Pass the Ticket", "tactic": "defense-evasion"},
    "T1550.004": {"name": "Web Session Cookie", "tactic": "defense-evasion"},
    "T1552": {"name": "Unsecured Credentials", "tactic": "credential-access"},
    "T1552.001": {"name": "Credentials In Files", "tactic": "credential-access"},
    "T1552.002": {"name": "Credentials in Registry", "tactic": "credential-access"},
    "T1552.003": {"name": "Shell History", "tactic": "credential-access"},
    "T1552.004": {"name": "Private Keys", "tactic": "credential-access"},
    "T1552.005": {"name": "Cloud Instance Metadata API", "tactic": "credential-access"},
    "T1552.006": {"name": "Group Policy Preferences", "tactic": "credential-access"},
    "T1552.007": {"name": "Container API", "tactic": "credential-access"},
    "T1552.008": {"name": "Chat Messages", "tactic": "credential-access"},
    "T1554": {"name": "Compromise Host Software Binary", "tactic": "persistence"},
    "T1555": {"name": "Credentials from Password Stores", "tactic": "credential-access"},
    "T1555.001": {"name": "Keychain", "tactic": "credential-access"},
    "T1555.002": {"name": "Securityd Memory", "tactic": "credential-access"},
    "T1555.003": {"name": "Credentials from Web Browsers", "tactic": "credential-access"},
    "T1555.004": {"name": "Windows Credential Manager", "tactic": "credential-access"},
    "T1555.005": {"name": "Password Managers", "tactic": "credential-access"},
    "T1555.006": {"name": "Cloud Secrets Management Stores", "tactic": "credential-access"},
    "T1556": {"name": "Modify Authentication Process", "tactic": "credential-access"},
    "T1556.001": {"name": "Domain Controller Authentication", "tactic": "credential-access"},
    "T1556.002": {"name": "Password Filter DLL", "tactic": "credential-access"},
    "T1556.003": {"name": "Pluggable Authentication Modules", "tactic": "credential-access"},
    "T1556.004": {"name": "Network Device Authentication", "tactic": "credential-access"},
    "T1556.005": {"name": "Reversible Encryption", "tactic": "credential-access"},
    "T1556.006": {"name": "Multi-Factor Authentication", "tactic": "credential-access"},
    "T1556.007": {"name": "Hybrid Identity", "tactic": "credential-access"},
    "T1556.008": {"name": "Network Provider DLL", "tactic": "credential-access"},
    "T1556.009": {"name": "Conditional Access Policies", "tactic": "credential-access"},
    "T1557": {"name": "Adversary-in-the-Middle", "tactic": "collection"},
    "T1557.001": {"name": "Name Resolution Poisoning and SMB Relay", "tactic": "collection"},
    "T1557.002": {"name": "ARP Cache Poisoning", "tactic": "collection"},
    "T1557.003": {"name": "DHCP Spoofing", "tactic": "collection"},
    "T1557.004": {"name": "Evil Twin", "tactic": "collection"},
    "T1558": {"name": "Steal or Forge Kerberos Tickets", "tactic": "credential-access"},
    "T1558.001": {"name": "Golden Ticket", "tactic": "credential-access"},
    "T1558.002": {"name": "Silver Ticket", "tactic": "credential-access"},
    "T1558.003": {"name": "Kerberoasting", "tactic": "credential-access"},
    "T1558.004": {"name": "AS-REP Roasting", "tactic": "credential-access"},
    "T1558.005": {"name": "Ccache Files", "tactic": "credential-access"},
    "T1559": {"name": "Inter-Process Communication", "tactic": "execution"},
    "T1559.001": {"name": "Component Object Model", "tactic": "execution"},
    "T1559.002": {"name": "Dynamic Data Exchange", "tactic": "execution"},
    "T1559.003": {"name": "XPC Services", "tactic": "execution"},
    "T1560": {"name": "Archive Collected Data", "tactic": "collection"},
    "T1560.001": {"name": "Archive via Utility", "tactic": "collection"},
    "T1560.002": {"name": "Archive via Library", "tactic": "collection"},
    "T1560.003": {"name": "Archive via Custom Method", "tactic": "collection"},
    "T1561": {"name": "Disk Wipe", "tactic": "impact"},
    "T1561.001": {"name": "Disk Content Wipe", "tactic": "impact"},
    "T1561.002": {"name": "Disk Structure Wipe", "tactic": "impact"},
    "T1562": {"name": "Impair Defenses", "tactic": "defense-evasion"},
    "T1563": {"name": "Remote Service Session Hijacking", "tactic": "lateral-movement"},
    "T1563.001": {"name": "SSH Hijacking", "tactic": "lateral-movement"},
    "T1563.002": {"name": "RDP Hijacking", "tactic": "lateral-movement"},
    "T1564": {"name": "Hide Artifacts", "tactic": "defense-evasion"},
    "T1564.001": {"name": "Hidden Files and Directories", "tactic": "defense-evasion"},
    "T1564.002": {"name": "Hidden Users", "tactic": "defense-evasion"},
    "T1564.003": {"name": "Hidden Window", "tactic": "defense-evasion"},
    "T1564.004": {"name": "NTFS File Attributes", "tactic": "defense-evasion"},
    "T1564.005": {"name": "Hidden File System", "tactic": "defense-evasion"},
    "T1564.006": {"name": "Run Virtual Instance", "tactic": "defense-evasion"},
    "T1564.007": {"name": "VBA Stomping", "tactic": "defense-evasion"},
    "T1564.008": {"name": "Email Hiding Rules", "tactic": "defense-evasion"},
    "T1564.009": {"name": "Resource Forking", "tactic": "defense-evasion"},
    "T1564.010": {"name": "Process Argument Spoofing", "tactic": "defense-evasion"},
    "T1564.011": {"name": "Ignore Process Interrupts", "tactic": "defense-evasion"},
    "T1564.012": {"name": "File/Path Exclusions", "tactic": "defense-evasion"},
    "T1564.013": {"name": "Bind Mounts", "tactic": "defense-evasion"},
    "T1564.014": {"name": "Extended Attributes", "tactic": "defense-evasion"},
    "T1565": {"name": "Data Manipulation", "tactic": "impact"},
    "T1565.001": {"name": "Stored Data Manipulation", "tactic": "impact"},
    "T1565.002": {"name": "Transmitted Data Manipulation", "tactic": "impact"},
    "T1565.003": {"name": "Runtime Data Manipulation", "tactic": "impact"},
    "T1566": {"name": "Phishing", "tactic": "initial-access"},
    "T1566.001": {"name": "Spearphishing Attachment", "tactic": "initial-access"},
    "T1566.002": {"name": "Spearphishing Link", "tactic": "initial-access"},
    "T1566.003": {"name": "Spearphishing via Service", "tactic": "initial-access"},
    "T1566.004": {"name": "Spearphishing Voice", "tactic": "initial-access"},
    "T1567": {"name": "Exfiltration Over Web Service", "tactic": "exfiltration"},
    "T1567.001": {"name": "Exfiltration to Code Repository", "tactic": "exfiltration"},
    "T1567.002": {"name": "Exfiltration to Cloud Storage", "tactic": "exfiltration"},
    "T1567.003": {"name": "Exfiltration to Text Storage Sites", "tactic": "exfiltration"},
    "T1567.004": {"name": "Exfiltration Over Webhook", "tactic": "exfiltration"},
    "T1568": {"name": "Dynamic Resolution", "tactic": "command-and-control"},
    "T1568.001": {"name": "Fast Flux DNS", "tactic": "command-and-control"},
    "T1568.002": {"name": "Domain Generation Algorithms", "tactic": "command-and-control"},
    "T1568.003": {"name": "DNS Calculation", "tactic": "command-and-control"},
    "T1569": {"name": "System Services", "tactic": "execution"},
    "T1569.001": {"name": "Launchctl", "tactic": "execution"},
    "T1569.002": {"name": "Service Execution", "tactic": "execution"},
    "T1569.003": {"name": "Systemctl", "tactic": "execution"},
    "T1570": {"name": "Lateral Tool Transfer", "tactic": "lateral-movement"},
    "T1571": {"name": "Non-Standard Port", "tactic": "command-and-control"},
    "T1572": {"name": "Protocol Tunneling", "tactic": "command-and-control"},
    "T1573": {"name": "Encrypted Channel", "tactic": "command-and-control"},
    "T1573.001": {"name": "Symmetric Cryptography", "tactic": "command-and-control"},
    "T1573.002": {"name": "Asymmetric Cryptography", "tactic": "command-and-control"},
    "T1574": {"name": "Hijack Execution Flow", "tactic": "defense-evasion"},
    "T1574.001": {"name": "DLL", "tactic": "defense-evasion"},
    "T1574.004": {"name": "Dylib Hijacking", "tactic": "defense-evasion"},
    "T1574.005": {"name": "Executable Installer File Permissions Weakness", "tactic": "defense-evasion"},
    "T1574.006": {"name": "Dynamic Linker Hijacking", "tactic": "defense-evasion"},
    "T1574.007": {"name": "Path Interception by PATH Environment Variable", "tactic": "defense-evasion"},
    "T1574.008": {"name": "Path Interception by Search Order Hijacking", "tactic": "defense-evasion"},
    "T1574.009": {"name": "Path Interception by Unquoted Path", "tactic": "defense-evasion"},
    "T1574.010": {"name": "Services File Permissions Weakness", "tactic": "defense-evasion"},
    "T1574.011": {"name": "Services Registry Permissions Weakness", "tactic": "defense-evasion"},
    "T1574.012": {"name": "COR_PROFILER", "tactic": "defense-evasion"},
    "T1574.013": {"name": "KernelCallbackTable", "tactic": "defense-evasion"},
    "T1574.014": {"name": "AppDomainManager", "tactic": "defense-evasion"},
    "T1580": {"name": "Cloud Infrastructure Discovery", "tactic": "discovery"},
    "T1583": {"name": "Acquire Infrastructure", "tactic": "resource-development"},
    "T1583.001": {"name": "Domains", "tactic": "resource-development"},
    "T1583.002": {"name": "DNS Server", "tactic": "resource-development"},
    "T1583.003": {"name": "Virtual Private Server", "tactic": "resource-development"},
    "T1583.004": {"name": "Server", "tactic": "resource-development"},
    "T1583.005": {"name": "Botnet", "tactic": "resource-development"},
    "T1583.006": {"name": "Web Services", "tactic": "resource-development"},
    "T1583.007": {"name": "Serverless", "tactic": "resource-development"},
    "T1583.008": {"name": "Malvertising", "tactic": "resource-development"},
    "T1584": {"name": "Compromise Infrastructure", "tactic": "resource-development"},
    "T1584.001": {"name": "Domains", "tactic": "resource-development"},
    "T1584.002": {"name": "DNS Server", "tactic": "resource-development"},
    "T1584.003": {"name": "Virtual Private Server", "tactic": "resource-development"},
    "T1584.004": {"name": "Server", "tactic": "resource-development"},
    "T1584.005": {"name": "Botnet", "tactic": "resource-development"},
    "T1584.006": {"name": "Web Services", "tactic": "resource-development"},
    "T1584.007": {"name": "Serverless", "tactic": "resource-development"},
    "T1584.008": {"name": "Network Devices", "tactic": "resource-development"},
    "T1585": {"name": "Establish Accounts", "tactic": "resource-development"},
    "T1585.001": {"name": "Social Media Accounts", "tactic": "resource-development"},
    "T1585.002": {"name": "Email Accounts", "tactic": "resource-development"},
    "T1585.003": {"name": "Cloud Accounts", "tactic": "resource-development"},
    "T1586": {"name": "Compromise Accounts", "tactic": "resource-development"},
    "T1586.001": {"name": "Social Media Accounts", "tactic": "resource-development"},
    "T1586.002": {"name": "Email Accounts", "tactic": "resource-development"},
    "T1586.003": {"name": "Cloud Accounts", "tactic": "resource-development"},
    "T1587": {"name": "Develop Capabilities", "tactic": "resource-development"},
    "T1587.001": {"name": "Malware", "tactic": "resource-development"},
    "T1587.002": {"name": "Code Signing Certificates", "tactic": "resource-development"},
    "T1587.003": {"name": "Digital Certificates", "tactic": "resource-development"},
    "T1587.004": {"name": "Exploits", "tactic": "resource-development"},
    "T1588": {"name": "Obtain Capabilities", "tactic": "resource-development"},
    "T1588.001": {"name": "Malware", "tactic": "resource-development"},
    "T1588.002": {"name": "Tool", "tactic": "resource-development"},
    "T1588.003": {"name": "Code Signing Certificates", "tactic": "resource-development"},
    "T1588.004": {"name": "Digital Certificates", "tactic": "resource-development"},
    "T1588.005": {"name": "Exploits", "tactic": "resource-development"},
    "T1588.006": {"name": "Vulnerabilities", "tactic": "resource-development"},
    "T1588.007": {"name": "Artificial Intelligence", "tactic": "resource-development"},
    "T1589": {"name": "Gather Victim Identity Information", "tactic": "reconnaissance"},
    "T1589.001": {"name": "Credentials", "tactic": "reconnaissance"},
    "T1589.002": {"name": "Email Addresses", "tactic": "reconnaissance"},
    "T1589.003": {"name": "Employee Names", "tactic": "reconnaissance"},
    "T1590": {"name": "Gather Victim Network Information", "tactic": "reconnaissance"},
    "T1590.001": {"name": "Domain Properties", "tactic": "reconnaissance"},
    "T1590.002": {"name": "DNS", "tactic": "reconnaissance"},
    "T1590.003": {"name": "Network Trust Dependencies", "tactic": "reconnaissance"},
    "T1590.004": {"name": "Network Topology", "tactic": "reconnaissance"},
    "T1590.005": {"name": "IP Addresses", "tactic": "reconnaissance"},
    "T1590.006": {"name": "Network Security Appliances", "tactic": "reconnaissance"},
    "T1591": {"name": "Gather Victim Org Information", "tactic": "reconnaissance"},
    "T1591.001": {"name": "Determine Physical Locations", "tactic": "reconnaissance"},
    "T1591.002": {"name": "Business Relationships", "tactic": "reconnaissance"},
    "T1591.003": {"name": "Identify Business Tempo", "tactic": "reconnaissance"},
    "T1591.004": {"name": "Identify Roles", "tactic": "reconnaissance"},
    "T1592": {"name": "Gather Victim Host Information", "tactic": "reconnaissance"},
    "T1592.001": {"name": "Hardware", "tactic": "reconnaissance"},
    "T1592.002": {"name": "Software", "tactic": "reconnaissance"},
    "T1592.003": {"name": "Firmware", "tactic": "reconnaissance"},
    "T1592.004": {"name": "Client Configurations", "tactic": "reconnaissance"},
    "T1593": {"name": "Search Open Websites/Domains", "tactic": "reconnaissance"},
    "T1593.001": {"name": "Social Media", "tactic": "reconnaissance"},
    "T1593.002": {"name": "Search Engines", "tactic": "reconnaissance"},
    "T1593.003": {"name": "Code Repositories", "tactic": "reconnaissance"},
    "T1594": {"name": "Search Victim-Owned Websites", "tactic": "reconnaissance"},
    "T1595": {"name": "Active Scanning", "tactic": "reconnaissance"},
    "T1595.001": {"name": "Scanning IP Blocks", "tactic": "reconnaissance"},
    "T1595.002": {"name": "Vulnerability Scanning", "tactic": "reconnaissance"},
    "T1595.003": {"name": "Wordlist Scanning", "tactic": "reconnaissance"},
    "T1596": {"name": "Search Open Technical Databases", "tactic": "reconnaissance"},
    "T1596.001": {"name": "DNS/Passive DNS", "tactic": "reconnaissance"},
    "T1596.002": {"name": "WHOIS", "tactic": "reconnaissance"},
    "T1596.003": {"name": "Digital Certificates", "tactic": "reconnaissance"},
    "T1596.004": {"name": "CDNs", "tactic": "reconnaissance"},
    "T1596.005": {"name": "Scan Databases", "tactic": "reconnaissance"},
    "T1597": {"name": "Search Closed Sources", "tactic": "reconnaissance"},
    "T1597.001": {"name": "Threat Intel Vendors", "tactic": "reconnaissance"},
    "T1597.002": {"name": "Purchase Technical Data", "tactic": "reconnaissance"},
    "T1598": {"name": "Phishing for Information", "tactic": "reconnaissance"},
    "T1598.001": {"name": "Spearphishing Service", "tactic": "reconnaissance"},
    "T1598.002": {"name": "Spearphishing Attachment", "tactic": "reconnaissance"},
    "T1598.003": {"name": "Spearphishing Link", "tactic": "reconnaissance"},
    "T1598.004": {"name": "Spearphishing Voice", "tactic": "reconnaissance"},
    "T1599": {"name": "Network Boundary Bridging", "tactic": "defense-evasion"},
    "T1599.001": {"name": "Network Address Translation Traversal", "tactic": "defense-evasion"},
    "T1600": {"name": "Weaken Encryption", "tactic": "defense-evasion"},
    "T1600.001": {"name": "Reduce Key Space", "tactic": "defense-evasion"},
    "T1600.002": {"name": "Disable Crypto Hardware", "tactic": "defense-evasion"},
    "T1601": {"name": "Modify System Image", "tactic": "defense-evasion"},
    "T1601.001": {"name": "Patch System Image", "tactic": "defense-evasion"},
    "T1601.002": {"name": "Downgrade System Image", "tactic": "defense-evasion"},
    "T1602": {"name": "Data from Configuration Repository", "tactic": "collection"},
    "T1602.001": {"name": "SNMP (MIB Dump)", "tactic": "collection"},
    "T1602.002": {"name": "Network Device Configuration Dump", "tactic": "collection"},
    "T1606": {"name": "Forge Web Credentials", "tactic": "credential-access"},
    "T1606.001": {"name": "Web Cookies", "tactic": "credential-access"},
    "T1606.002": {"name": "SAML Tokens", "tactic": "credential-access"},
    "T1608": {"name": "Stage Capabilities", "tactic": "resource-development"},
    "T1608.001": {"name": "Upload Malware", "tactic": "resource-development"},
    "T1608.002": {"name": "Upload Tool", "tactic": "resource-development"},
    "T1608.003": {"name": "Install Digital Certificate", "tactic": "resource-development"},
    "T1608.004": {"name": "Drive-by Target", "tactic": "resource-development"},
    "T1608.005": {"name": "Link Target", "tactic": "resource-development"},
    "T1608.006": {"name": "SEO Poisoning", "tactic": "resource-development"},
    "T1609": {"name": "Container Administration Command", "tactic": "execution"},
    "T1610": {"name": "Deploy Container", "tactic": "defense-evasion"},
    "T1611": {"name": "Escape to Host", "tactic": "privilege-escalation"},
    "T1612": {"name": "Build Image on Host", "tactic": "defense-evasion"},
    "T1613": {"name": "Container and Resource Discovery", "tactic": "discovery"},
    "T1614": {"name": "System Location Discovery", "tactic": "discovery"},
    "T1614.001": {"name": "System Language Discovery", "tactic": "discovery"},
    "T1615": {"name": "Group Policy Discovery", "tactic": "discovery"},
    "T1619": {"name": "Cloud Storage Object Discovery", "tactic": "discovery"},
    "T1620": {"name": "Reflective Code Loading", "tactic": "defense-evasion"},
    "T1621": {"name": "Multi-Factor Authentication Request Generation", "tactic": "credential-access"},
    "T1622": {"name": "Debugger Evasion", "tactic": "defense-evasion"},
    "T1647": {"name": "Plist File Modification", "tactic": "defense-evasion"},
    "T1648": {"name": "Serverless Execution", "tactic": "execution"},
    "T1649": {"name": "Steal or Forge Authentication Certificates", "tactic": "credential-access"},
    "T1650": {"name": "Acquire Access", "tactic": "resource-development"},
    "T1651": {"name": "Cloud Administration Command", "tactic": "execution"},
    "T1652": {"name": "Device Driver Discovery", "tactic": "discovery"},
    "T1653": {"name": "Power Settings", "tactic": "persistence"},
    "T1654": {"name": "Log Enumeration", "tactic": "discovery"},
    "T1656": {"name": "Impersonation", "tactic": "defense-evasion"},
    "T1657": {"name": "Financial Theft", "tactic": "impact"},
    "T1659": {"name": "Content Injection", "tactic": "command-and-control"},
    "T1665": {"name": "Hide Infrastructure", "tactic": "command-and-control"},
    "T1667": {"name": "Email Bombing", "tactic": "impact"},
    "T1668": {"name": "Exclusive Control", "tactic": "persistence"},
    "T1669": {"name": "Wi-Fi Networks", "tactic": "initial-access"},
    "T1671": {"name": "Cloud Application Integration", "tactic": "persistence"},
    "T1673": {"name": "Virtual Machine Discovery", "tactic": "discovery"},
    "T1674": {"name": "Input Injection", "tactic": "execution"},
    "T1675": {"name": "ESXi Administration Command", "tactic": "execution"},
    "T1677": {"name": "Poisoned Pipeline Execution", "tactic": "execution"},
    "T1678": {"name": "Delay Execution", "tactic": "defense-evasion"},
    "T1679": {"name": "Selective Exclusion", "tactic": "defense-evasion"},
    "T1680": {"name": "Local Storage Discovery", "tactic": "discovery"},
    "T1681": {"name": "Search Threat Vendor Data", "tactic": "reconnaissance"},
    "T1682": {"name": "Query Public AI Services", "tactic": "reconnaissance"},
    "T1683": {"name": "Generate Content", "tactic": "resource-development"},
    "T1683.001": {"name": "Written Content", "tactic": "resource-development"},
    "T1683.002": {"name": "Audio-Visual Content", "tactic": "resource-development"},
    "T1684": {"name": "Social Engineering", "tactic": "defense-evasion"},
    "T1684.001": {"name": "Impersonation", "tactic": "defense-evasion"},
    "T1684.002": {"name": "Email Spoofing", "tactic": "defense-evasion"},
    "T1685": {"name": "Disable or Modify Tools", "tactic": "defense-evasion"},
    "T1685.001": {"name": "Disable or Modify Windows Event Log", "tactic": "defense-evasion"},
    "T1685.002": {"name": "Disable or Modify Cloud Log", "tactic": "defense-evasion"},
    "T1685.003": {"name": "Modify or Spoof Tool UI", "tactic": "defense-evasion"},
    "T1685.004": {"name": "Disable or Modify Linux Audit System Log", "tactic": "defense-evasion"},
    "T1685.005": {"name": "Clear Windows Event Logs", "tactic": "defense-evasion"},
    "T1686": {"name": "Disable or Modify System Firewall", "tactic": "defense-evasion"},
    "T1686.001": {"name": "Cloud Firewall", "tactic": "defense-evasion"},
    "T1686.002": {"name": "Network Device Firewall", "tactic": "defense-evasion"},
    "T1686.003": {"name": "Windows Host Firewall", "tactic": "defense-evasion"},
}


def extract_ttps_regex(text: str) -> list[dict]:
    """Return explicitly cited T-IDs found in text, names/tactics from lookup."""
    found = sorted(set(TECHNIQUE_RE.findall(text.upper())))
    return [
        {
            "technique_id":   tid,
            "technique_name": TECHNIQUE_LOOKUP.get(tid, {}).get("name"),
            "tactic":         TECHNIQUE_LOOKUP.get(tid, {}).get("tactic"),
        }
        for tid in found
    ]


def extract_ttps_ai(text: str, api_key: str) -> list[dict]:
    """Use Claude Haiku to infer ATT&CK techniques from prose."""
    try:
        from anthropic import Anthropic
        client = Anthropic(api_key=api_key)
        snippet = text[:MAX_TEXT_CHARS]
        msg = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=600,
            messages=[{
                "role": "user",
                "content": (
                    "You are a MITRE ATT&CK analyst. Extract attack techniques from "
                    "the security article below.\n\n"
                    "Return ONLY a JSON array. Each element must have:\n"
                    "  technique_id   — ATT&CK ID e.g. T1566.001\n"
                    "  technique_name — short name e.g. Spearphishing Attachment\n"
                    "  tactic         — tactic slug e.g. initial-access\n\n"
                    "Rules:\n"
                    "- Only include techniques clearly described or demonstrated.\n"
                    "- Do not hallucinate. If uncertain, omit.\n"
                    "- Return [] if nothing found.\n"
                    "- Output raw JSON, no markdown fences.\n\n"
                    f"Article:\n{snippet}"
                ),
            }],
        )
        raw = msg.content[0].text.strip()
        raw = re.sub(r'^```(?:json)?\s*|\s*```$', '', raw, flags=re.MULTILINE)
        parsed = json.loads(raw)
        if not isinstance(parsed, list):
            return []
        result = []
        for t in parsed:
            tid = (t.get("technique_id") or "").upper().strip()
            if re.match(r'^T\d{4}(\.\d{3})?$', tid):
                # prefer AI name/tactic; fall back to lookup if AI left them blank
                lookup = TECHNIQUE_LOOKUP.get(tid, {})
                name = (t.get("technique_name") or "").strip() or lookup.get("name")
                tactic = (t.get("tactic") or "").strip().lower() or lookup.get("tactic")
                result.append({
                    "technique_id":   tid,
                    "technique_name": name or None,
                    "tactic":         tactic or None,
                })
        return result
    except Exception as e:
        print(f"TTP AI extraction failed: {e}")
        return []


def extract_ttps(text: str, api_key: str = "") -> list[dict]:
    """Merge regex + AI results, deduped by technique_id."""
    regex_hits = extract_ttps_regex(text)

    if not api_key:
        return regex_hits

    ai_hits = extract_ttps_ai(text, api_key)

    # AI results are richer (have names/tactics); regex fills gaps
    merged: dict[str, dict] = {t["technique_id"]: t for t in ai_hits}
    for t in regex_hits:
        if t["technique_id"] not in merged:
            merged[t["technique_id"]] = t

    return list(merged.values())
